.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. adnetcoin_qt test_adnetcoin_qt
clean: FORCE
	$(MAKE) -C .. adnetcoin_qt_clean test_adnetcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_adnetcoin_qt_check
adnetcoin-qt adnetcoin-qt.exe: FORCE
	 $(MAKE) -C .. adnetcoin_qt
